// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMewwIwmV15VWA3pWGINlA5CpZ14FuBVk',
    appId: '1:59204674157:web:a0821e7b194cab79da9564',
    messagingSenderId: '59204674157',
    projectId: 'spotter-4627a',
    authDomain: 'spotter-4627a.firebaseapp.com',
    databaseURL: 'https://spotter-4627a-default-rtdb.firebaseio.com',
    storageBucket: 'spotter-4627a.appspot.com',
    measurementId: 'G-N0S2R84ME4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfk3fklIo2PxLF3WmoNYSg4LH6qTaGZno',
    appId: '1:59204674157:android:78e488d76782b3aada9564',
    messagingSenderId: '59204674157',
    projectId: 'spotter-4627a',
    databaseURL: 'https://spotter-4627a-default-rtdb.firebaseio.com',
    storageBucket: 'spotter-4627a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeWPshlwBigZbh-zviuWkcH050dlIqsU',
    appId: '1:59204674157:ios:c1dd9c3e09dacf81da9564',
    messagingSenderId: '59204674157',
    projectId: 'spotter-4627a',
    databaseURL: 'https://spotter-4627a-default-rtdb.firebaseio.com',
    storageBucket: 'spotter-4627a.appspot.com',
    iosClientId: '59204674157-nrj73pv57dl4r0s4nob9fd78opgke78d.apps.googleusercontent.com',
    iosBundleId: 'com.loucy.spotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeWPshlwBigZbh-zviuWkcH050dlIqsU',
    appId: '1:59204674157:ios:c1dd9c3e09dacf81da9564',
    messagingSenderId: '59204674157',
    projectId: 'spotter-4627a',
    databaseURL: 'https://spotter-4627a-default-rtdb.firebaseio.com',
    storageBucket: 'spotter-4627a.appspot.com',
    iosClientId: '59204674157-nrj73pv57dl4r0s4nob9fd78opgke78d.apps.googleusercontent.com',
    iosBundleId: 'com.loucy.spotter',
  );
}
